# frontend/Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# Copia SOLO los manifests primero para cachear la instalación
COPY package*.json ./

# IMPORTANTE: instalar devDependencies
# (no uses --omit=dev ni NODE_ENV=production)
RUN npm ci

# Ahora sí, copia el resto del código
COPY . .

EXPOSE 5173
CMD ["npm","run","dev","--","--host","0.0.0.0"]
