# frontend/Dockerfile.dev
FROM node:22-bookworm-slim

WORKDIR /app
ENV CI=true

# Copiamos manifests para cache de deps
COPY package*.json ./

# Si tienes package-lock.json, usa npm ci. Si no lo tienes, usa npm install:
# RUN npm ci
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

# Copiamos el resto del código
COPY . .

EXPOSE 5173
CMD ["npm","run","dev","--","--host","0.0.0.0"]
